public enum BlockType
{
    Air = 0,
    Grass = 1,
    Dirt = 2,
    Stone = 3,
    Sand = 4,
    Water = 5,
    Bedrock = 6,
    Leaves = 7,
    Log = 8,
    Deepslate = 9,
    Snow = 10,
    glass = 11,
    glowstone = 12,
    oak_planks = 13,
    short_grass4 = 14,
    birch_log = 15,
    Crafter = 16,
    CoalOre = 17,
    IronOre = 18,
    GoldOre = 19,
    RedstoneOre = 20,
    DiamondOre = 21,
    EmeraldOre = 22,
    Cactus = 23,
    acacia_log = 24,
}
